// <auto-generated />
namespace ModeloDDD_AV2.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MaisICollections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MaisICollections));
        
        string IMigrationMetadata.Id
        {
            get { return "201612112150271_MaisICollections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
